security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
 
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
       # ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                username_parameter: email
                password_parameter: password
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_sala_index
            logout:
                path: app_logout
                target: app_login
            remember_me:
                lifetime: 1800  # 30 minutos
                secret: '%kernel.secret%'
                path: /
 

    # Control de acceso simplificado
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }